import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page}>
        <div className={styles.page__header} >
          <Header />
          <div className={styles.header__content}>
            <div className={styles.header__content__text}>
              <h5 className={styles.tag}>Join Us</h5>
              <h1 className={styles.title}>A Great Place to <br /> Receive Care</h1>
              <h4 className={styles.sub__title}>DentalCare is most focused in <br /> helping you discover your most <br /> beauiful smile</h4>
              <div className={styles.header__content__button}>
                <button className={styles.sub__join}>Join Us</button>
                <button className={styles.More}>Learn More</button>
              </div>
              <div />
              <div className={styles.header__content__images}>
                <Image
                  src="/img 3.png"
                  alt="image 3"
                  className={styles.img3}
                  width={212.73}
                  height={212.73}
                  priority
                />

              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
